apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy-lab
  name: oauth2-proxy-lab
data:
  oauth2_proxy.cfg: |-
    cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
    #cookie_domain = ".localtest.me"
    whitelist_domains=[".localtest.me"]
    # only users with this domain will be let in
    email_domains=["example.com"]
    
    client_id="oauth2-proxy"
    client_secret="b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
    cookie_secure="false"
    redirect_url="http://oauth2-proxy.localtest.me/oauth2/callback"
    
    # we don't want to proxy anything so pick a non-existent directory
    upstreams = [ "file:///dev/null" ]
    
    # return authenticated user to nginx
    set_xauthrequest = true
    # using http://dex.localtest.me/.well-known/openid-configuration oauth2-proxy will populate
    # login_url, redeem_url, and oidc_jwks_url
    provider="oidc"
    oidc_issuer_url="http://dex.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy-lab
  name: oauth2-proxy-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy-lab
  template:
    metadata:
      labels:
        app: oauth2-proxy-lab
    spec:
      containers:
      - name: oauth2-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.3.0"
        imagePullPolicy: IfNotPresent
        args:
          - --http-address=0.0.0.0:4180
          - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        ports:
          - containerPort: 4180
            name: http
            protocol: TCP
        volumeMounts:
        - mountPath: /etc/oauth2_proxy
          name: config
        resources: 
      volumes:
      - configMap:
          defaultMode: 420
          name: oauth2-proxy-lab
        name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy-lab
  name: oauth2-proxy-lab
spec:
  ports:
  - name: http
    port: 4180
    targetPort: 4180
  selector:
    app: oauth2-proxy-lab
  type: ClusterIP